name: bluetooth_chat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences_service:
    git:
      url: https://github.com/sari-shehada/shared_preferences_service.git
      ref: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/app_icon.png

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-THinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Lato-Thin.ttf
          weight: 100
        - asset: fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-BlackItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Lato-Black.ttf
          weight: 700